[main]
network = mainnet
datadir = /home/berzat-babur/Desktop/berzcoin/.tmp_mainnet_run
allow_missing_bootstrap = true
rpcbind = 127.0.0.1
rpcport = 29443
bind = 127.0.0.1
port = 29444
wallet_encryption_passphrase = local-mainnet-passphrase-for-run
