[main]
network = mainnet
datadir = /home/berzat-babur/Desktop/bitcoin/BerzCoin/.runtime/interface-mainnet

disablewallet = false

webdashboard = true
webhost = 127.0.0.1
webport = 18080

rpcbind = 127.0.0.1
rpcport = 28543
rpcallowip = 127.0.0.1

bind = 127.0.0.1
port = 28544
addnode = 127.0.0.1:18444

mining = false
autominer = false
miningaddress =
mining_threads = 1
mining_target_time_secs = 60
coinbase_maturity = 1
mining_require_wallet_match = false

dnsseed = false
debug = true
