services:
  berzcoin-node:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
    container_name: berzcoin-node
    restart: unless-stopped
    ports:
      - "8333:8333"
      - "8332:8332"
    volumes:
      - berzcoin-data:/var/lib/berzcoin
    command: ["-datadir", "/var/lib/berzcoin"]

volumes:
  berzcoin-data:
