[main]
network = mainnet
datadir = /home/berzat-babur/Desktop/berzcoin/.tmp_join
port = 8333
rpcbind = 127.0.0.1
rpcport = 9333
dnsseed = false
allow_missing_bootstrap = true
addnode = seed.berzcoin.net:8333
