[main]
network = mainnet
datadir = /home/berzat-babur/Desktop/bitcoin/BerzCoin/.runtime/mainnet
port = 18444
bind = 0.0.0.0
rpcbind = 127.0.0.1
rpcport = 18443
rpcallowip = 127.0.0.1
rpc_require_auth = false
logfile = debug.log
# Discovery enabled
dnsseed = true
bootstrap_enabled = true
allow_missing_bootstrap = true
# Keep open peer slots for testing
maxconnections = 125
maxoutbound = 8
